#include "ui/cache_control.h"

#include <errno.h>
#include <string.h>
#include <unistd.h>

#include <lvgl/src/misc/cache/instance/lv_image_cache.h>

#include "utils/log.h"

#define EPASS_TEMP_APP_LAUNCHER "/tmp/appstart"

void ui_cache_clear(ui_cache_clear_result_t *result) {
    if(result == NULL) {
        return;
    }

    memset(result, 0, sizeof(*result));

    /*
     * Passing NULL invalidates all decoded images and their cached headers.
     * LVGL will decode any image still needed by the current/future screen again.
     */
    lv_image_cache_drop(NULL);
    result->image_cache_cleared = true;

    /*
     * This launcher is generated by drm_app_neo immediately before it exits to
     * start a foreground app.  While the UI is running, any existing copy is
     * stale and can be removed safely.
     */
    if(unlink(EPASS_TEMP_APP_LAUNCHER) == 0) {
        result->launcher_file_removed = true;
        log_info("removed stale app launcher: %s", EPASS_TEMP_APP_LAUNCHER);
        return;
    }

    if(errno != ENOENT) {
        result->launcher_file_error = errno;
        log_warn("failed to remove %s: %s", EPASS_TEMP_APP_LAUNCHER,
                 strerror(errno));
    }
}
